name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14' # Use the Node.js version you need

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Install sshpass
      run: sudo apt-get install sshpass

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: ${{ secrets.VPS_PORT }}  # Default SSH port is 22; you can omit this if you're using the default.
        script: |
          cd /root/app/
          git pull
          npm install
          npm run build
          pm2 restart ecosystem.config.js
          sudo systemctl restart nginx
